backend:
  name: github
  repo: jiun8631/jiun8631  # 替換成你的GitHub用戶名和倉庫名
  branch: main  # 或者是master，看你的預設分支
  auth_endpoint: /auth

# 使用你現有的圖片路徑
media_folder: "static/img"           # 圖片存放在你現有的static/img資料夾
public_folder: "/img"                # 圖片公開訪問路徑 /img

editor:
  preview: true

# 自訂預覽樣式
preview_path: "{{slug}}"

collections:
  - name: "blog"
    label: "部落格文章"
    folder: "content/post"             # 使用你現有的content/post路徑
    create: true
    slug: "{{slug}}"                   # 可自訂檔名格式
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "作者", name: "author", widget: "string", default: "HAO"}
      - {label: "描述", name: "description", widget: "text", required: false}
      - {label: "標籤", name: "tags", widget: "list", required: false}
      - {label: "關鍵字", name: "keywords", widget: "list", required: false}
      - {label: "發布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "是否置頂", name: "pinned", widget: "boolean", default: false}
      
      # 圖片物件配置（對應你的複雜image結構）
      - label: "特色圖片設定"
        name: "image" 
        widget: "object"
        fields:
          - {label: "圖片路徑", name: "src", widget: "image"}
          - {label: "圖片描述", name: "alt", widget: "string"}
          - label: "縮圖設定"
            name: "thumbnail"
            widget: "object"
            fields:
              - {label: "尺寸", name: "size", widget: "string", default: "170px"}
              - {label: "邊框樣式", name: "borders", widget: "select", options: ["rounded", "square"], default: "rounded"}
      
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "分類", name: "categories", widget: "list", required: false}
      - {label: "內容", name: "body", widget: "markdown"}

  # 如果你有其他頁面需要編輯，可以添加
  - name: "pages"
    label: "其他頁面"
    files:
      - label: "關於頁面"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "標題", name: "title", widget: "string"}
          - {label: "內容", name: "body", widget: "markdown"}